# Use the official Node.js image from the Docker Hub
FROM node:20.11.0

# Set a working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Command to run your app using Node.js
CMD ["npm run dev"]
